language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

mysql:
  database: jrtancock_blog_test
  username: jrtancock
  encoding: utf8

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - mysql -e "create database IF NOT EXISTS blog_test;" -uroot

script:
  - phpunit

notifications:
  email: false
