language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5
      env: PHPCS=1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - mysql -e "create database IF NOT EXISTS blog_test;" -uroot

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot; fi"

notifications:
  email: false
